-- Add AI Persona fields to profiles table (mapped from user's 'members' table request)
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS ai_persona JSONB,
ADD COLUMN IF NOT EXISTS activity_tags TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS similarity_score FLOAT DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
-- Additional fields required for persona generation
ADD COLUMN IF NOT EXISTS professional_field TEXT,
ADD COLUMN IF NOT EXISTS organization TEXT,
ADD COLUMN IF NOT EXISTS join_date TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Create member_tags table
CREATE TABLE IF NOT EXISTS member_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  tag_name VARCHAR(50),
  tag_weight FLOAT DEFAULT 1.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for member_tags
ALTER TABLE member_tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own tags" ON member_tags
  FOR SELECT USING (auth.uid() = member_id);

CREATE POLICY "Admins can view all tags" ON member_tags
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid() AND profiles.role = 'admin'
    )
  );

-- Create member_activities table (for tracking behavior)
CREATE TABLE IF NOT EXISTS member_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  activity_type VARCHAR(50), -- e.g., 'login', 'post', 'comment', 'attend_event'
  activity_desc TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for member_activities
ALTER TABLE member_activities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own activities" ON member_activities
  FOR SELECT USING (auth.uid() = member_id);

CREATE POLICY "Users can insert their own activities" ON member_activities
  FOR INSERT WITH CHECK (auth.uid() = member_id);

-- Add some dummy activities for testing (Optional, can be run manually if needed)
-- INSERT INTO member_activities (member_id, activity_type, activity_desc)
-- VALUES (auth.uid(), 'login', 'Logged in to dashboard');
