-- 1. Enable Database Extensions (if not already enabled)
-- create extension if not exists vector; -- Required for embeddings if you plan to use them later

-- 2. Update profiles table (Using 'profiles' as it is the main table in this system, corresponding to 'members')
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS ai_persona JSONB,
ADD COLUMN IF NOT EXISTS activity_tags TEXT[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS similarity_score FLOAT DEFAULT 0,
ADD COLUMN IF NOT EXISTS professional_field TEXT, -- Added for persona generation
ADD COLUMN IF NOT EXISTS join_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(), -- Added for "Senior Member" calculation
ADD COLUMN IF NOT EXISTS last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 3. Create member_tags table
CREATE TABLE IF NOT EXISTS member_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    tag_name VARCHAR(50),
    tag_weight FLOAT DEFAULT 1.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Enable RLS on new table
ALTER TABLE member_tags ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies for member_tags
-- Allow users to read their own tags
CREATE POLICY "Users can view own tags" ON member_tags
    FOR SELECT USING (auth.uid() = member_id);

-- Allow admins to view all tags (Assuming admin check function exists or similar logic)
-- You might need to adjust this based on your admin logic, e.g.:
-- CREATE POLICY "Admins can view all tags" ON member_tags
--     FOR ALL USING ( public.is_admin() );
